# First Non-Repeating Element
#
# Goal:
# Return the first item, in original input order, whose total frequency is one.
# Return None when the input is empty or no item occurs exactly once.
#
# Base contract assumptions:
# - "First" means the earliest item in the original input sequence.
# - Items may repeat and may appear in any order.
# - The input is a complete, bounded batch.
# - We can only determine that an item is globally non-repeating after processing
#   the entire batch, because a later item may repeat an earlier value.
#
# Why use two passes?
# - Pass 1 establishes a global fact: the total frequency of every item.
# - Pass 2 applies the ordering requirement: return the earliest item with a
#   total count of exactly one.
#
# Complexity:
# - Time: at most 2n iterations, which simplifies to O(n).
# - Space: O(u), where u is the number of distinct items; O(n) worst case.
#
# -------------------------------------------------------------------------------
# Customer / FDE extrapolation
# -------------------------------------------------------------------------------
#
# In a customer-facing system, "first item" is ambiguous and must be defined
# before choosing an algorithm or optimizing performance.
#
# For example, a request to "find the first failure for a customer" could mean:
# - The earliest event generated by the customer's application (event time).
# - The first event received by our telemetry pipeline (ingestion/arrival time).
# - The first failure that was visible to the customer.
# - The first failure that was not automatically recovered by a retry.
# - The first failure requiring support or customer action.
# - The first result in a stable UI, audit, or incident-review ordering.
#
# These meanings may produce different answers. In distributed systems, events
# can arrive late or out of order, so input/ingestion order may differ from the
# order in which events actually occurred.
#
# Example customer contract:
# "For one tenant and a requested time range, return the earliest customer-visible,
# unrecovered failed request by event timestamp. If timestamps tie, use event_id
# as a deterministic tie-breaker. Exclude duplicate deliveries and preserve the
# trace_id for support investigation."
#
# Before implementation, clarify:
# - What identifies the customer or tenant, and what authorization boundaries apply?
# - What makes an event eligible: failed status, customer-visible impact, severity,
#   an unrecovered retry, or another business rule?
# - What does "first" mean: event time, ingestion time, UI order, or priority?
# - Is the ordering field guaranteed, trusted, and consistently populated?
# - What is the tie-breaker when two events have the same ordering value?
# - Is this a complete batch or a continuous stream?
# - Can records be duplicated, missing, replayed, late, or out of order?
# - Must the answer be exact and final, or can it be provisional and later revised?
# - What time window, latency target, memory budget, and volume must be supported?
#
# Design implications:
# - If input is sorted by the authoritative ordering field, return the first
#   qualifying item and terminate early.
# - If input is unsorted, scan all records and retain the best qualifying candidate.
# - If this is a stream, define late-arrival/watermark behavior and whether a late
#   event may revise a previously returned result.
# - Do not replace an exact ordered result with "any qualifying item" unless the
#   customer agrees that deterministic/chronological ordering has no value.


def first_non_repeating(items: list[str]) -> str | None:
    """
    Return the first item in input order with total frequency one.

    This is a bounded-batch implementation. It is appropriate when the original
    input order is authoritative and the answer must be exact for the full batch.
    """

    # Maps every distinct item to its total count across the full input batch.
    counts: dict[str, int] = {}

    # Pass 1: Count all items before deciding which ones are globally unique.
    # A value seen once so far is not necessarily non-repeating; it may occur later.
    for item in items:
        counts[item] = counts.get(item, 0) + 1

    # Pass 2: Scan the original sequence so "first" retains its contract meaning.
    for item in items:
        if counts[item] == 1:
            # Early termination is correct: this is the earliest qualifying item
            # according to original input order.
            return item

    # Explicit no-result behavior:
    # - Empty input has no qualifying item.
    # - An input where every item repeats has no qualifying item.
    return None


def run_test(items: list[str], expected: str | None) -> None:
    """Run one test case and print the expected and actual result."""

    actual = first_non_repeating(items)
    passed = actual == expected

    print(f"Input:    {items}")
    print(f"Expected: {expected!r}")
    print(f"Actual:   {actual!r}")
    print(f"Result:   {'PASS' if passed else 'FAIL'}")
    print("-" * 60)


if __name__ == "__main__":
    # Normal case: both "c" and "d" are unique, but "c" is first in input order.
    run_test(
        items=["a", "b", "a", "c", "b", "d"],
        expected="c",
    )

    # A value that appears unique initially can repeat later in the input.
    run_test(
        items=["a", "b", "a", "b", "c"],
        expected="c",
    )

    # Empty-batch behavior.
    run_test(
        items=[],
        expected=None,
    )

    # No item has a total frequency of one.
    run_test(
        items=["a", "b", "a", "b"],
        expected=None,
    )

    # Every item is unique, so return the first item.
    run_test(
        items=["x", "y", "z"],
        expected="x",
    )